name: Release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    working-directory: mcp-sentinel-python

jobs:
  build-python-artifacts:
    name: Build wheel & sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Build
        run: poetry build --no-interaction

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: mcp-sentinel-python/dist/
